#연습 문제
#1. YAML 파일을 사용하여 app=nginx 레이블을 가진 파드를 생성하라.
#2. app=nginx를 가진 파드를 get하라. get된 파드의 레이블의 app을 확인하라.
#3. app=nginx 레이블을 가진 파드에 team=dev1 레이블을 추가하라.

apiVersion: v1 # core 그룹은 생략 가능
kind: Pod
metadata:
  name: nginx-label
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80

