# 연습 문제
# 전체 네임스페이스에 존재하는 configmap과 secret 개수는 몇 개인가? 16
# secret 데이터에는 어떤 secret data가 포함돼 있는가? 3

# 다음과 같이 Mysql 서버를 지원하는 secret-mysql.yaml을 생성하자.
# Secret Name: db-secret
# Secret Data 1: DB_Password=1q2w3e4r

# Mysql 이미지를 하나 생성하고 앞서 만든 secret을 환경 변수 이름과 연결하자.
# Image: mysql:5.6
# Port 번호: 3306
# 환경 변수 name: MYSQL_ROOT_PASSWORD # 컨테이너 개발자가 정한다.

# 잘 적용됐는지 확인할 수 있는 명령어: 
# kubectl exec -it mysql -- mysql -u root -p
# password: 1q2w3e4r 

apiVersion: v1
kind: Pod
metadata:
  name: mysql
spec:
  containers:
  - name: mysql
    image: mysql:5.6
    env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: db-secret 
            key: DB_Password