# 연습 문제
# 다음 요구사항에 맞는 deploy를 구현하라.
# Deploy name: nginx
# Image: nginx
# 최소 요구사항
# CPU: 1m
# 메모리: 200Mi
# 리소스 제한
# CPU: 2m
# 메모리: 400Mi
# Port: 80
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-resource-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "200Mi"
            cpu: "1m"
          limits:
            memory: "400Mi"
            cpu: "2m"