apiVersion: v1
kind: Pod
metadata:
  name: mongo
spec:
  nodeName: ip-10-0-94-77.ec2.internal
  containers:
    - name: mongo
      image: mongo
      volumeMounts:
      - mountPath: "/data/db"
        name: data-volume
  volumes:
    - name: data-volume
      persistentVolumeClaim:
        claimName: mongo-pvc # pvc 이름과 일치해야 한다.