apiVersion: v1
kind: Pod
metadata:
  name: count-httpd
spec:
  containers:
  # count
  - image: gasbugs/count
    name: html-generator
    volumeMounts:
    - mountPath: /var/htdocs # 컨테이너 개발자가 정한다.
      name: html-volume
  # httpd
  - image: httpd
    name: web-server
    volumeMounts:
    - mountPath: /usr/local/apache2/htdocs/ # 컨테이너 개발자가 정한다.
      name: html-volume
      readOnly: true # 권한을 지정하면 쓰기 불가 
  # 볼륨의 정의 
  volumes:
  - name: html-volume
    emptyDir: {}