#연습 문제
#같은 emptyDir을 공유하는 프로세스를 만들어 통신하기
#하나의 프로세스는 랜덤한 값을 생성 (gasbugs/count 이미지 사용)
#하나의 프로세스는 랜덤한 값을 출력 (nginx 이미지 사용)
apiVersion: v1
kind: Pod
metadata:
  name: count-nginx
spec:
  containers:
  # count
  - image: gasbugs/count
    name: html-generator
    volumeMounts:
    - mountPath: /var/htdocs # 컨테이너 개발자가 정한다.
      name: html-volume
  # nginx
  - image: nginx
    name: web-server
    volumeMounts:
    - mountPath: /usr/share/nginx/html # 컨테이너 개발자가 정한다.
      name: html-volume
      readOnly: true # 권한을 지정하면 쓰기 불가 
  # 볼륨의 정의 
  volumes:
  - name: html-volume
    emptyDir: {}