apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc-to-slow
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  storageClassName: slow
  